locations:
  - pathPrefix: /ws/kkd-configuration-service
    protocol: ws
    targetModule: kkd-configuration-service
  - pathPrefix: /api/kkd-configuration-service
    protocol: http
    targetModule: kkd-configuration-service
  - pathPrefix: /api
    protocol: grpc
    skipAuth: false
    targetModule: router
